name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: APSS892
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Criar pasta dist
        run: mkdir -p dist

      - name: Verificar arquivos gerados
        run: ls -la dist/

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
